<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Menggunakan truncate() untuk mengosongkan tabel dan mereset ID.
        DB::table('foods')->truncate();

        $foods = [
            ['name' => 'Abon Ikan', 'calories' => 370, 'carbs' => 8.0, 'protein' => 40.0, 'fat' => 18.0],
            ['name' => 'Abon Sapi', 'calories' => 435, 'carbs' => 28.0, 'protein' => 35.0, 'fat' => 20.0],
            ['name' => 'Alpukat', 'calories' => 160, 'carbs' => 8.5, 'protein' => 2.0, 'fat' => 14.7],
            ['name' => 'Anggur', 'calories' => 69, 'carbs' => 18.1, 'protein' => 0.7, 'fat' => 0.2],
            ['name' => 'Apel', 'calories' => 52, 'carbs' => 13.8, 'protein' => 0.3, 'fat' => 0.2],
            ['name' => 'Apple Cinnamon Oatmeal', 'calories' => 150, 'carbs' => 30.0, 'protein' => 5.0, 'fat' => 2.5],
            ['name' => 'Asinan Bogor', 'calories' => 125, 'carbs' => 28.0, 'protein' => 2.0, 'fat' => 0.5],
            ['name' => 'Asinan Sayur', 'calories' => 85, 'carbs' => 15.2, 'protein' => 2.5, 'fat' => 1.8],
            ['name' => 'Ayam Bakar (dada)', 'calories' => 165, 'carbs' => 0.0, 'protein' => 31.0, 'fat' => 3.6],
            ['name' => 'Ayam Betutu', 'calories' => 170, 'carbs' => 2.5, 'protein' => 20.5, 'fat' => 8.5],
            ['name' => 'Ayam Geprek Saus Keju', 'calories' => 350, 'carbs' => 15.0, 'protein' => 25.0, 'fat' => 20.0],
            ['name' => 'Ayam Goreng (paha, tepung)', 'calories' => 289, 'carbs' => 0.0, 'protein' => 30.6, 'fat' => 17.8],
            ['name' => 'Ayam Goreng Kalasan, Paha', 'calories' => 260, 'carbs' => 2.0, 'protein' => 28.0, 'fat' => 15.0],
            ['name' => 'Ayam Goreng Kentucky, Paha', 'calories' => 280, 'carbs' => 8.0, 'protein' => 26.0, 'fat' => 16.0],
            ['name' => 'Ayam Goreng Mentega', 'calories' => 305, 'carbs' => 5.0, 'protein' => 25.0, 'fat' => 20.0],
            ['name' => 'Ayam Goreng Tepung', 'calories' => 260, 'carbs' => 11.0, 'protein' => 27.0, 'fat' => 11.5],
            ['name' => 'Ayam Kecap', 'calories' => 240, 'carbs' => 10.0, 'protein' => 22.0, 'fat' => 12.0],
            ['name' => 'Ayam Pop', 'calories' => 265, 'carbs' => 0.0, 'protein' => 25.5, 'fat' => 18.0],
            ['name' => 'Ayam Rica-Rica', 'calories' => 190, 'carbs' => 4.5, 'protein' => 20.0, 'fat' => 10.0],
            ['name' => 'Ayam Saus Jamur', 'calories' => 180, 'carbs' => 7.0, 'protein' => 21.0, 'fat' => 8.0],
            ['name' => 'Ayam Saus Tiram', 'calories' => 210, 'carbs' => 6.0, 'protein' => 21.0, 'fat' => 11.0],
            ['name' => 'Ayam Taliwang, Masakan', 'calories' => 180, 'carbs' => 3.0, 'protein' => 22.0, 'fat' => 9.0],
            ['name' => 'Ayam Woku', 'calories' => 175, 'carbs' => 4.0, 'protein' => 21.0, 'fat' => 8.0],
            ['name' => 'Bakmi Goreng', 'calories' => 200, 'carbs' => 29.0, 'protein' => 8.0, 'fat' => 6.0],
            ['name' => 'Bakpao Daging', 'calories' => 230, 'carbs' => 35.0, 'protein' => 10.0, 'fat' => 5.0],
            ['name' => 'Bakso Sapi (kuah)', 'calories' => 55, 'carbs' => 5.0, 'protein' => 5.2, 'fat' => 1.6],
            ['name' => 'Bakso Sapi (per biji, sedang)', 'calories' => 35, 'carbs' => 1.8, 'protein' => 3.3, 'fat' => 1.5],
            ['name' => 'Bakwan', 'calories' => 137, 'carbs' => 8.1, 'protein' => 3.2, 'fat' => 9.8],
            ['name' => 'Bakwan Jagung', 'calories' => 110, 'carbs' => 15.0, 'protein' => 3.0, 'fat' => 4.5],
            ['name' => 'Bandeng Presto Goreng', 'calories' => 295, 'carbs' => 0.0, 'protein' => 20.0, 'fat' => 23.0],
            ['name' => 'Bantal (kue)', 'calories' => 280, 'carbs' => 40.0, 'protein' => 5.0, 'fat' => 10.0],
            ['name' => 'Batagor', 'calories' => 285, 'carbs' => 25.0, 'protein' => 10.0, 'fat' => 16.0],
            ['name' => 'Bebek Goreng', 'calories' => 320, 'carbs' => 0.0, 'protein' => 23.0, 'fat' => 25.0],
            ['name' => 'Beef Burger', 'calories' => 295, 'carbs' => 24.0, 'protein' => 17.0, 'fat' => 15.0],
            ['name' => 'Beef Teriyaki', 'calories' => 220, 'carbs' => 10.0, 'protein' => 20.0, 'fat' => 11.0],
            ['name' => 'Beras Merah, Nasi', 'calories' => 111, 'carbs' => 23.0, 'protein' => 2.6, 'fat' => 0.9],
            ['name' => 'Bihun Goreng', 'calories' => 192, 'carbs' => 24.5, 'protein' => 8.2, 'fat' => 6.8],
            ['name' => 'Bihun Goreng Instan', 'calories' => 360, 'carbs' => 52.0, 'protein' => 7.0, 'fat' => 13.0],
            ['name' => 'Bihun Kari Ayam', 'calories' => 250, 'carbs' => 30.0, 'protein' => 10.0, 'fat' => 9.0],
            ['name' => 'Bihun Rebus', 'calories' => 109, 'carbs' => 24.0, 'protein' => 1.2, 'fat' => 0.2],
            ['name' => 'Bika Ambon', 'calories' => 325, 'carbs' => 60.0, 'protein' => 5.0, 'fat' => 7.0],
            ['name' => 'Bingka', 'calories' => 230, 'carbs' => 38.0, 'protein' => 4.0, 'fat' => 7.0],
            ['name' => 'Biskuit (marie)', 'calories' => 450, 'carbs' => 75.0, 'protein' => 8.0, 'fat' => 12.0],
            ['name' => 'Bobor Bayam', 'calories' => 60, 'carbs' => 6.0, 'protein' => 2.0, 'fat' => 3.0],
            ['name' => 'Bolu Peca', 'calories' => 290, 'carbs' => 60.0, 'protein' => 4.0, 'fat' => 4.0],
            ['name' => 'Bolu Kukus', 'calories' => 280, 'carbs' => 55.0, 'protein' => 6.0, 'fat' => 4.0],
            ['name' => 'Breakfast Cup', 'calories' => 220, 'carbs' => 15.0, 'protein' => 12.0, 'fat' => 12.0],
            ['name' => 'Brokoli', 'calories' => 34, 'carbs' => 6.6, 'protein' => 2.8, 'fat' => 0.4],
            ['name' => 'Brongkos Daging', 'calories' => 185, 'carbs' => 10.0, 'protein' => 18.0, 'fat' => 8.0],
            ['name' => 'Bubur Ayam', 'calories' => 90, 'carbs' => 16.0, 'protein' => 3.0, 'fat' => 1.5],
            ['name' => 'Bubur Kacang Hijau', 'calories' => 150, 'carbs' => 25.0, 'protein' => 7.0, 'fat' => 2.5],
            ['name' => 'Bubur Ketan Hitam', 'calories' => 165, 'carbs' => 35.0, 'protein' => 4.0, 'fat' => 1.5],
            ['name' => 'Bubur Nasi Blender', 'calories' => 60, 'carbs' => 12.0, 'protein' => 1.5, 'fat' => 0.5],
            ['name' => 'Bubur Tinotuan (Manado)', 'calories' => 95, 'carbs' => 18.0, 'protein' => 3.0, 'fat' => 1.0],
            ['name' => 'Bulgogi', 'calories' => 210, 'carbs' => 8.0, 'protein' => 22.0, 'fat' => 10.0],
            ['name' => 'Cakalang Asar (Asap)', 'calories' => 130, 'carbs' => 0.0, 'protein' => 28.0, 'fat' => 1.5],
            ['name' => 'Cake Tape', 'calories' => 260, 'carbs' => 45.0, 'protein' => 4.0, 'fat' => 7.0],
            ['name' => 'Capcay Goreng', 'calories' => 75, 'carbs' => 6.5, 'protein' => 4.5, 'fat' => 3.5],
            ['name' => 'Capcay Kuah', 'calories' => 55, 'carbs' => 5.0, 'protein' => 3.5, 'fat' => 2.0],
            ['name' => 'Cendol (dengan santan & gula)', 'calories' => 180, 'carbs' => 38.0, 'protein' => 1.5, 'fat' => 3.0],
            ['name' => 'Chicken Teriyaki', 'calories' => 200, 'carbs' => 12.0, 'protein' => 20.0, 'fat' => 8.0],
            ['name' => 'Chocolate Milk Pudding', 'calories' => 140, 'carbs' => 22.0, 'protein' => 4.0, 'fat' => 4.0],
            ['name' => 'Cilok (dengan saus kacang)', 'calories' => 145, 'carbs' => 28.0, 'protein' => 2.5, 'fat' => 2.0],
            ['name' => 'Cireng Goreng', 'calories' => 190, 'carbs' => 40.0, 'protein' => 1.0, 'fat' => 2.5],
            ['name' => 'Combro', 'calories' => 130, 'carbs' => 20.0, 'protein' => 2.0, 'fat' => 4.5],
            ['name' => 'Creamy Chicken Teriyaki', 'calories' => 250, 'carbs' => 12.0, 'protein' => 20.0, 'fat' => 14.0],
            ['name' => 'Cumi Asam Manis', 'calories' => 130, 'carbs' => 10.0, 'protein' => 18.0, 'fat' => 2.0],
            ['name' => 'Cumi Goreng Tepung', 'calories' => 180, 'carbs' => 9.5, 'protein' => 16.0, 'fat' => 8.5],
            ['name' => 'Dadar Gulung', 'calories' => 145, 'carbs' => 28.0, 'protein' => 3.0, 'fat' => 2.5],
            ['name' => 'Daging Sapi (Has Dalam)', 'calories' => 143, 'carbs' => 0.0, 'protein' => 26.3, 'fat' => 3.5],
            ['name' => 'Dendeng Balado', 'calories' => 350, 'carbs' => 10.0, 'protein' => 28.0, 'fat' => 20.0],
            ['name' => 'Dendeng Belut Goreng', 'calories' => 303, 'carbs' => 0.0, 'protein' => 14.0, 'fat' => 27.0],
            ['name' => 'Dendeng Mujahir Goreng', 'calories' => 280, 'carbs' => 0.0, 'protein' => 30.0, 'fat' => 17.0],
            ['name' => 'Dodol Manado', 'calories' => 370, 'carbs' => 80.0, 'protein' => 2.0, 'fat' => 4.0],
            ['name' => 'Donat Kentang', 'calories' => 335, 'carbs' => 45.0, 'protein' => 6.0, 'fat' => 15.0],
            ['name' => 'Durian', 'calories' => 147, 'carbs' => 27.1, 'protein' => 1.5, 'fat' => 5.3],
            ['name' => 'Empal (Daging) Goreng', 'calories' => 340, 'carbs' => 2.0, 'protein' => 28.0, 'fat' => 24.0],
            ['name' => 'Empal Gentong', 'calories' => 150, 'carbs' => 5.0, 'protein' => 15.0, 'fat' => 8.0],
            ['name' => 'Emping (Kerupuk Melinjo)', 'calories' => 480, 'carbs' => 72.0, 'protein' => 9.0, 'fat' => 17.0],
            ['name' => 'Enting-Enting Wijen', 'calories' => 510, 'carbs' => 50.0, 'protein' => 12.0, 'fat' => 28.0],
            ['name' => 'Es Buah', 'calories' => 140, 'carbs' => 30.0, 'protein' => 1.0, 'fat' => 2.0],
            ['name' => 'Es Cincau', 'calories' => 120, 'carbs' => 25.0, 'protein' => 1.0, 'fat' => 1.5],
            ['name' => 'Es Doger', 'calories' => 200, 'carbs' => 35.0, 'protein' => 3.0, 'fat' => 5.0],
            ['name' => 'Es Teh Manis', 'calories' => 70, 'carbs' => 18.0, 'protein' => 0.0, 'fat' => 0.0],
            ['name' => 'Fuyunghai', 'calories' => 210, 'carbs' => 8.0, 'protein' => 12.0, 'fat' => 14.0],
            ['name' => 'Gado-gado (dengan saus)', 'calories' => 137, 'carbs' => 13.5, 'protein' => 6.2, 'fat' => 6.9],
            ['name' => 'Garang Asem Ayam', 'calories' => 160, 'carbs' => 3.0, 'protein' => 18.0, 'fat' => 8.5],
            ['name' => 'Gemblong', 'calories' => 200, 'carbs' => 40.0, 'protein' => 2.0, 'fat' => 3.0],
            ['name' => 'Geplak', 'calories' => 390, 'carbs' => 88.0, 'protein' => 1.0, 'fat' => 2.0],
            ['name' => 'Gudeg Nangka', 'calories' => 160, 'carbs' => 30.0, 'protein' => 3.0, 'fat' => 3.2],
            ['name' => 'Gulai Ayam', 'calories' => 175, 'carbs' => 4.0, 'protein' => 18.0, 'fat' => 10.0],
            ['name' => 'Gulai Ikan', 'calories' => 150, 'carbs' => 3.0, 'protein' => 16.0, 'fat' => 8.0],
            ['name' => 'Gulai Ikan Paya', 'calories' => 155, 'carbs' => 4.0, 'protein' => 17.0, 'fat' => 8.0],
            ['name' => 'Gulai Kambing', 'calories' => 180, 'carbs' => 3.0, 'protein' => 15.0, 'fat' => 12.0],
            ['name' => 'Gulai Keumamah', 'calories' => 160, 'carbs' => 4.0, 'protein' => 20.0, 'fat' => 7.0],
            ['name' => 'Gulai Telor Cabai Hijau', 'calories' => 180, 'carbs' => 5.0, 'protein' => 10.0, 'fat' => 13.0],
            ['name' => 'Gulai Tiram', 'calories' => 120, 'carbs' => 6.0, 'protein' => 12.0, 'fat' => 5.0],
            ['name' => 'Gurame Asem Manis', 'calories' => 190, 'carbs' => 15.0, 'protein' => 18.0, 'fat' => 6.0],
            ['name' => 'Ikan Kuah Pindang', 'calories' => 110, 'carbs' => 2.0, 'protein' => 18.0, 'fat' => 3.0],
            ['name' => 'Ikan Mas Pepes', 'calories' => 120, 'carbs' => 2.0, 'protein' => 16.0, 'fat' => 5.0],
            ['name' => 'Ikan Kembung Bakar', 'calories' => 125, 'carbs' => 0.0, 'protein' => 21.3, 'fat' => 3.4],
            ['name' => 'Ikan Lele Goreng', 'calories' => 105, 'carbs' => 0.0, 'protein' => 18.0, 'fat' => 3.0],
            ['name' => 'Jagung Muda Rebus', 'calories' => 80, 'carbs' => 18.0, 'protein' => 3.0, 'fat' => 1.0],
            ['name' => 'Jeruk Manis, Segar', 'calories' => 47, 'carbs' => 12.0, 'protein' => 0.9, 'fat' => 0.1],
            ['name' => 'Jus Alpukat (gula & susu)', 'calories' => 250, 'carbs' => 30.0, 'protein' => 3.0, 'fat' => 14.0],
            ['name' => 'Jus Apel', 'calories' => 110, 'carbs' => 28.0, 'protein' => 0.5, 'fat' => 0.3],
            ['name' => 'Jus Belimbing', 'calories' => 90, 'carbs' => 22.0, 'protein' => 1.0, 'fat' => 0.5],
            ['name' => 'Jus Jeruk', 'calories' => 112, 'carbs' => 26.0, 'protein' => 1.7, 'fat' => 0.5],
            ['name' => 'Jus Mangga', 'calories' => 135, 'carbs' => 35.0, 'protein' => 1.0, 'fat' => 0.5],
            ['name' => 'Jus Melon', 'calories' => 80, 'carbs' => 20.0, 'protein' => 1.0, 'fat' => 0.4],
            ['name' => 'Jus Nanas', 'calories' => 120, 'carbs' => 30.0, 'protein' => 1.0, 'fat' => 0.2],
            ['name' => 'Jus Pir', 'calories' => 130, 'carbs' => 33.0, 'protein' => 1.0, 'fat' => 0.3],
            ['name' => 'Jus Semangka', 'calories' => 71, 'carbs' => 18.0, 'protein' => 1.4, 'fat' => 0.4],
            ['name' => 'Jus Sirsak', 'calories' => 140, 'carbs' => 35.0, 'protein' => 1.5, 'fat' => 0.5],
            ['name' => 'Jus Strawberry', 'calories' => 85, 'carbs' => 20.0, 'protein' => 1.0, 'fat' => 0.5],
            ['name' => 'Jus Tomat', 'calories' => 41, 'carbs' => 9.0, 'protein' => 1.6, 'fat' => 0.4],
            ['name' => 'Jus Wortel', 'calories' => 94, 'carbs' => 22.0, 'protein' => 2.2, 'fat' => 0.4],
            ['name' => 'Kacang Atom', 'calories' => 500, 'carbs' => 40.0, 'protein' => 15.0, 'fat' => 30.0],
            ['name' => 'Kacang Goyang', 'calories' => 490, 'carbs' => 60.0, 'protein' => 10.0, 'fat' => 22.0],
            ['name' => 'Kacang Sukro', 'calories' => 510, 'carbs' => 38.0, 'protein' => 14.0, 'fat' => 32.0],
            ['name' => 'Kaholeo', 'calories' => 160, 'carbs' => 35.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Karedok', 'calories' => 120, 'carbs' => 12.0, 'protein' => 5.0, 'fat' => 6.0],
            ['name' => 'Kelapa Muda, Air, Segar', 'calories' => 19, 'carbs' => 3.7, 'protein' => 0.7, 'fat' => 0.2],
            ['name' => 'Kembang Tahu', 'calories' => 80, 'carbs' => 15.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Keripik Bayam', 'calories' => 450, 'carbs' => 50.0, 'protein' => 10.0, 'fat' => 22.0],
            ['name' => 'Keripik Kentang', 'calories' => 536, 'carbs' => 53.0, 'protein' => 7.0, 'fat' => 35.0],
            ['name' => 'Keripik Singkong', 'calories' => 480, 'carbs' => 70.0, 'protein' => 2.0, 'fat' => 22.0],
            ['name' => 'Keripik Tempe', 'calories' => 520, 'carbs' => 45.0, 'protein' => 18.0, 'fat' => 30.0],
            ['name' => 'Keripik Ubi', 'calories' => 490, 'carbs' => 75.0, 'protein' => 1.5, 'fat' => 21.0],
            ['name' => 'Kerupuk Udang', 'calories' => 475, 'carbs' => 65.0, 'protein' => 1.0, 'fat' => 23.0],
            ['name' => 'Ketan Hitam, Matang', 'calories' => 140, 'carbs' => 32.0, 'protein' => 3.5, 'fat' => 0.5],
            ['name' => 'Ketan Hitam, Tapai', 'calories' => 166, 'carbs' => 36.0, 'protein' => 4.0, 'fat' => 0.7],
            ['name' => 'Ketan Putih, Matang', 'calories' => 135, 'carbs' => 30.0, 'protein' => 2.8, 'fat' => 0.3],
            ['name' => 'Ketan Putih, Tapai', 'calories' => 170, 'carbs' => 38.0, 'protein' => 3.0, 'fat' => 0.5],
            ['name' => 'Ketan, Ketupat', 'calories' => 130, 'carbs' => 29.0, 'protein' => 2.0, 'fat' => 0.2],
            ['name' => 'Ketoprak', 'calories' => 155, 'carbs' => 25.0, 'protein' => 6.0, 'fat' => 3.5],
            ['name' => 'Ketupat Kandangan', 'calories' => 250, 'carbs' => 30.0, 'protein' => 12.0, 'fat' => 9.0],
            ['name' => 'Kue Apem', 'calories' => 140, 'carbs' => 30.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Kue Bakpia', 'calories' => 150, 'carbs' => 28.0, 'protein' => 4.0, 'fat' => 2.5],
            ['name' => 'Kue Jahe', 'calories' => 350, 'carbs' => 70.0, 'protein' => 4.0, 'fat' => 6.0],
            ['name' => 'Kue Kelepon', 'calories' => 130, 'carbs' => 28.0, 'protein' => 1.5, 'fat' => 1.5],
            ['name' => 'Kue Lumpur', 'calories' => 160, 'carbs' => 28.0, 'protein' => 3.0, 'fat' => 4.0],
            ['name' => 'Kue Pelita', 'calories' => 180, 'carbs' => 35.0, 'protein' => 2.0, 'fat' => 3.0],
            ['name' => 'Kue Putu Cangkir', 'calories' => 160, 'carbs' => 35.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Kwaci', 'calories' => 584, 'carbs' => 20.0, 'protein' => 21.0, 'fat' => 51.0],
            ['name' => 'Kwetiau Goreng', 'calories' => 190, 'carbs' => 28.0, 'protein' => 7.0, 'fat' => 5.5],
            ['name' => 'Laksa/Putu Mayang', 'calories' => 150, 'carbs' => 35.0, 'protein' => 1.5, 'fat' => 0.5],
            ['name' => 'Lapis Legit', 'calories' => 480, 'carbs' => 55.0, 'protein' => 8.0, 'fat' => 25.0],
            ['name' => 'Lontong Sayur', 'calories' => 130, 'carbs' => 22.0, 'protein' => 4.0, 'fat' => 3.0],
            ['name' => 'Lupis Ketan', 'calories' => 180, 'carbs' => 40.0, 'protein' => 3.0, 'fat' => 1.0],
            ['name' => 'Macaroni Sup', 'calories' => 120, 'carbs' => 15.0, 'protein' => 5.0, 'fat' => 4.0],
            ['name' => 'Martabak India', 'calories' => 220, 'carbs' => 20.0, 'protein' => 10.0, 'fat' => 11.0],
            ['name' => 'Martabak Mesir', 'calories' => 230, 'carbs' => 22.0, 'protein' => 11.0, 'fat' => 11.0],
            ['name' => 'Martabak Telur', 'calories' => 195, 'carbs' => 15.0, 'protein' => 8.0, 'fat' => 11.0],
            ['name' => 'Mie Aceh Rebus', 'calories' => 280, 'carbs' => 35.0, 'protein' => 12.0, 'fat' => 10.0],
            ['name' => 'Mie Ayam', 'calories' => 320, 'carbs' => 40.0, 'protein' => 15.0, 'fat' => 10.0],
            ['name' => 'Mie Bakso', 'calories' => 280, 'carbs' => 35.0, 'protein' => 12.0, 'fat' => 9.0],
            ['name' => 'Mie Kering', 'calories' => 350, 'carbs' => 75.0, 'protein' => 10.0, 'fat' => 1.5],
            ['name' => 'Mie Pangsit Basah', 'calories' => 260, 'carbs' => 32.0, 'protein' => 11.0, 'fat' => 9.0],
            ['name' => 'Mie Susu Keju', 'calories' => 420, 'carbs' => 55.0, 'protein' => 12.0, 'fat' => 16.0],
            ['name' => 'Milky Beef Bulgogi', 'calories' => 260, 'carbs' => 10.0, 'protein' => 22.0, 'fat' => 15.0],
            ['name' => 'Misoa', 'calories' => 360, 'carbs' => 78.0, 'protein' => 9.0, 'fat' => 1.0],
            ['name' => 'Misoa Goreng', 'calories' => 220, 'carbs' => 25.0, 'protein' => 8.0, 'fat' => 10.0],
            ['name' => 'Moon Tahu', 'calories' => 130, 'carbs' => 10.0, 'protein' => 8.0, 'fat' => 6.0],
            ['name' => 'Nasi', 'calories' => 130, 'carbs' => 28.2, 'protein' => 2.7, 'fat' => 0.3],
            ['name' => 'Nasi Daun Jeruk', 'calories' => 150, 'carbs' => 30.0, 'protein' => 3.0, 'fat' => 2.0],
            ['name' => 'Nasi Gemuk', 'calories' => 200, 'carbs' => 35.0, 'protein' => 4.0, 'fat' => 5.0],
            ['name' => 'Nasi Goreng', 'calories' => 168, 'carbs' => 27.5, 'protein' => 6.5, 'fat' => 3.8],
            ['name' => 'Nasi Kuning', 'calories' => 160, 'carbs' => 30.0, 'protein' => 3.0, 'fat' => 2.5],
            ['name' => 'Nasi Minyak', 'calories' => 210, 'carbs' => 36.0, 'protein' => 3.5, 'fat' => 5.5],
            ['name' => 'Nasi Pecel Sayur', 'calories' => 180, 'carbs' => 25.0, 'protein' => 8.0, 'fat' => 5.0],
            ['name' => 'Nasi Putih', 'calories' => 130, 'carbs' => 28.2, 'protein' => 2.7, 'fat' => 0.3],
            ['name' => 'Nasi Rames', 'calories' => 280, 'carbs' => 40.0, 'protein' => 10.0, 'fat' => 8.0],
            ['name' => 'Nasi Siram Udang', 'calories' => 240, 'carbs' => 30.0, 'protein' => 12.0, 'fat' => 8.0],
            ['name' => 'Nasi Tim', 'calories' => 180, 'carbs' => 28.0, 'protein' => 8.0, 'fat' => 4.0],
            ['name' => 'Nasi Uduk', 'calories' => 170, 'carbs' => 32.0, 'protein' => 3.5, 'fat' => 2.5],
            ['name' => 'Omelet Mie', 'calories' => 250, 'carbs' => 20.0, 'protein' => 10.0, 'fat' => 14.0],
            ['name' => 'Oncom', 'calories' => 120, 'carbs' => 8.0, 'protein' => 12.0, 'fat' => 4.0],
            ['name' => 'Onde-onde', 'calories' => 195, 'carbs' => 30.0, 'protein' => 4.0, 'fat' => 6.5],
            ['name' => 'Opor Ayam', 'calories' => 163, 'carbs' => 3.5, 'protein' => 19.5, 'fat' => 8.7],
            ['name' => 'Orak-Arik Telur Sayur', 'calories' => 160, 'carbs' => 5.0, 'protein' => 10.0, 'fat' => 11.0],
            ['name' => 'Oseng Sapi Kecombrang', 'calories' => 190, 'carbs' => 6.0, 'protein' => 20.0, 'fat' => 9.0],
            ['name' => 'Padamaran', 'calories' => 170, 'carbs' => 38.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Pangsit Kuah Susu', 'calories' => 200, 'carbs' => 20.0, 'protein' => 8.0, 'fat' => 9.0],
            ['name' => 'Papeda', 'calories' => 50, 'carbs' => 12.0, 'protein' => 0.5, 'fat' => 0.1],
            ['name' => 'Pastel', 'calories' => 250, 'carbs' => 25.0, 'protein' => 6.0, 'fat' => 14.0],
            ['name' => 'Pelecing Kangkung', 'calories' => 50, 'carbs' => 8.0, 'protein' => 3.0, 'fat' => 1.0],
            ['name' => 'Pempek Adaan', 'calories' => 180, 'carbs' => 20.0, 'protein' => 8.0, 'fat' => 7.0],
            ['name' => 'Pempek Belida', 'calories' => 190, 'carbs' => 22.0, 'protein' => 10.0, 'fat' => 7.0],
            ['name' => 'Pempek Kapal Selam', 'calories' => 315, 'carbs' => 40.0, 'protein' => 12.0, 'fat' => 12.0],
            ['name' => 'Pempek Kelesan', 'calories' => 170, 'carbs' => 18.0, 'protein' => 8.0, 'fat' => 7.0],
            ['name' => 'Pempek Kulit', 'calories' => 220, 'carbs' => 15.0, 'protein' => 9.0, 'fat' => 13.0],
            ['name' => 'Pempek Telur', 'calories' => 250, 'carbs' => 30.0, 'protein' => 10.0, 'fat' => 10.0],
            ['name' => 'Pempek Tenggiri', 'calories' => 180, 'carbs' => 20.0, 'protein' => 9.0, 'fat' => 7.0],
            ['name' => 'Perkedel Kentang', 'calories' => 80, 'carbs' => 10.0, 'protein' => 2.0, 'fat' => 3.5],
            ['name' => 'Pisang Goreng', 'calories' => 140, 'carbs' => 22.0, 'protein' => 1.0, 'fat' => 5.0],
            ['name' => 'Pulut', 'calories' => 135, 'carbs' => 30.0, 'protein' => 2.8, 'fat' => 0.3],
            ['name' => 'Pundut Nasi', 'calories' => 150, 'carbs' => 32.0, 'protein' => 3.0, 'fat' => 1.0],
            ['name' => 'Putri Selat', 'calories' => 180, 'carbs' => 38.0, 'protein' => 2.0, 'fat' => 2.0],
            ['name' => 'Rawon', 'calories' => 135, 'carbs' => 5.0, 'protein' => 15.0, 'fat' => 6.5],
            ['name' => 'Rawon Daging', 'calories' => 135, 'carbs' => 5.0, 'protein' => 15.0, 'fat' => 6.5],
            ['name' => 'Rempeyek Kacang Tanah', 'calories' => 520, 'carbs' => 50.0, 'protein' => 15.0, 'fat' => 28.0],
            ['name' => 'Rendang Sapi', 'calories' => 195, 'carbs' => 7.8, 'protein' => 22.8, 'fat' => 7.9],
            ['name' => 'Renggi Goreng', 'calories' => 450, 'carbs' => 80.0, 'protein' => 5.0, 'fat' => 12.0],
            ['name' => 'Roti', 'calories' => 265, 'carbs' => 49.0, 'protein' => 9.0, 'fat' => 3.2],
            ['name' => 'Roti Putih', 'calories' => 265, 'carbs' => 49.0, 'protein' => 9.0, 'fat' => 3.2],
            ['name' => 'Roti Tawar Gandum', 'calories' => 250, 'carbs' => 45.0, 'protein' => 9.0, 'fat' => 3.0],
            ['name' => 'Rujak Cingur', 'calories' => 200, 'carbs' => 20.0, 'protein' => 10.0, 'fat' => 9.0],
            ['name' => 'Sagu Lemak (Kue Sagon)', 'calories' => 450, 'carbs' => 75.0, 'protein' => 4.0, 'fat' => 15.0],
            ['name' => 'Salad Kentang', 'calories' => 143, 'carbs' => 15.0, 'protein' => 2.5, 'fat' => 8.0],
            ['name' => 'Sambal Goreng Kentang Ati', 'calories' => 125, 'carbs' => 15.0, 'protein' => 6.0, 'fat' => 4.5],
            ['name' => 'Sapi, Abon', 'calories' => 435, 'carbs' => 28.0, 'protein' => 35.0, 'fat' => 20.0],
            ['name' => 'Sapi, Paru, Goreng', 'calories' => 330, 'carbs' => 0.0, 'protein' => 25.0, 'fat' => 25.0],
            ['name' => 'Sarimuka', 'calories' => 220, 'carbs' => 45.0, 'protein' => 3.0, 'fat' => 3.0],
            ['name' => 'Sate Ayam (dengan saus)', 'calories' => 215, 'carbs' => 14.0, 'protein' => 26.0, 'fat' => 6.0],
            ['name' => 'Sate Bandeng', 'calories' => 180, 'carbs' => 2.0, 'protein' => 20.0, 'fat' => 10.0],
            ['name' => 'Sate Kambing', 'calories' => 205, 'carbs' => 0.0, 'protein' => 30.0, 'fat' => 9.0],
            ['name' => 'Sayur Asem', 'calories' => 40, 'carbs' => 8.0, 'protein' => 1.5, 'fat' => 0.4],
            ['name' => 'Sayur Bunga Pepaya', 'calories' => 45, 'carbs' => 7.0, 'protein' => 2.5, 'fat' => 1.0],
            ['name' => 'Sayur Cap Cai', 'calories' => 75, 'carbs' => 6.5, 'protein' => 4.5, 'fat' => 3.5],
            ['name' => 'Sayur Gudeg', 'calories' => 160, 'carbs' => 30.0, 'protein' => 3.0, 'fat' => 3.2],
            ['name' => 'Sayur Karedok', 'calories' => 120, 'carbs' => 12.0, 'protein' => 5.0, 'fat' => 6.0],
            ['name' => 'Sayur Lodeh', 'calories' => 60, 'carbs' => 6.0, 'protein' => 2.5, 'fat' => 3.0],
            ['name' => 'Sayur Sop', 'calories' => 36, 'carbs' => 6.2, 'protein' => 1.5, 'fat' => 0.5],
            ['name' => 'Semur Daging Cincang', 'calories' => 200, 'carbs' => 7.0, 'protein' => 18.0, 'fat' => 11.0],
            ['name' => 'Semur Daging Sapi', 'calories' => 180, 'carbs' => 8.0, 'protein' => 20.0, 'fat' => 7.0],
            ['name' => 'Semur Jengkol', 'calories' => 160, 'carbs' => 28.0, 'protein' => 6.0, 'fat' => 3.0],
            ['name' => 'Siomay Ikan', 'calories' => 115, 'carbs' => 12.0, 'protein' => 8.0, 'fat' => 4.0],
            ['name' => 'Sop Buntut', 'calories' => 195, 'carbs' => 4.0, 'protein' => 15.0, 'fat' => 13.0],
            ['name' => 'Sop Daging Sapi', 'calories' => 130, 'carbs' => 3.0, 'protein' => 16.0, 'fat' => 6.0],
            ['name' => 'Sop Kaki Sapi', 'calories' => 220, 'carbs' => 2.0, 'protein' => 18.0, 'fat' => 16.0],
            ['name' => 'Sop Kambing', 'calories' => 140, 'carbs' => 2.5, 'protein' => 15.0, 'fat' => 8.0],
            ['name' => 'Sop Konro', 'calories' => 250, 'carbs' => 5.0, 'protein' => 20.0, 'fat' => 17.0],
            ['name' => 'Sop Saudara', 'calories' => 180, 'carbs' => 6.0, 'protein' => 16.0, 'fat' => 10.0],
            ['name' => 'Sop Sayur Baso', 'calories' => 70, 'carbs' => 8.0, 'protein' => 5.0, 'fat' => 2.0],
            ['name' => 'Soto Ayam (bening)', 'calories' => 95, 'carbs' => 5.0, 'protein' => 10.0, 'fat' => 4.0],
            ['name' => 'Soto Bandung', 'calories' => 120, 'carbs' => 8.0, 'protein' => 12.0, 'fat' => 4.0],
            ['name' => 'Soto Banjar', 'calories' => 150, 'carbs' => 15.0, 'protein' => 12.0, 'fat' => 4.5],
            ['name' => 'Soto Betawi', 'calories' => 145, 'carbs' => 4.0, 'protein' => 12.0, 'fat' => 9.0],
            ['name' => 'Soto Betawi (daging, santan)', 'calories' => 145, 'carbs' => 4.0, 'protein' => 12.0, 'fat' => 9.0],
            ['name' => 'Soto Daging', 'calories' => 130, 'carbs' => 3.0, 'protein' => 16.0, 'fat' => 6.0],
            ['name' => 'Soto Jeroan', 'calories' => 180, 'carbs' => 2.0, 'protein' => 15.0, 'fat' => 12.0],
            ['name' => 'Soto Madura', 'calories' => 160, 'carbs' => 5.0, 'protein' => 15.0, 'fat' => 9.0],
            ['name' => 'Soto Padang', 'calories' => 150, 'carbs' => 10.0, 'protein' => 14.0, 'fat' => 6.0],
            ['name' => 'Soto Pekalongan', 'calories' => 140, 'carbs' => 7.0, 'protein' => 13.0, 'fat' => 6.0],
            ['name' => 'Soto Pemalang', 'calories' => 135, 'carbs' => 6.0, 'protein' => 14.0, 'fat' => 5.0],
            ['name' => 'Soto Sukaraja', 'calories' => 130, 'carbs' => 12.0, 'protein' => 10.0, 'fat' => 4.0],
            ['name' => 'Soto Sulung', 'calories' => 170, 'carbs' => 4.0, 'protein' => 16.0, 'fat' => 10.0],
            ['name' => 'Spaghetti', 'calories' => 160, 'carbs' => 22.0, 'protein' => 8.0, 'fat' => 4.5],
            ['name' => 'Srikaya Ketan', 'calories' => 240, 'carbs' => 50.0, 'protein' => 4.0, 'fat' => 3.0],
            ['name' => 'Sukiyaki', 'calories' => 180, 'carbs' => 10.0, 'protein' => 15.0, 'fat' => 8.0],
            ['name' => 'Sup Ayam', 'calories' => 80, 'carbs' => 5.0, 'protein' => 8.0, 'fat' => 3.0],
            ['name' => 'Sup Bola Tahu', 'calories' => 100, 'carbs' => 6.0, 'protein' => 7.0, 'fat' => 5.0],
            ['name' => 'Sup Telur Tomat', 'calories' => 90, 'carbs' => 7.0, 'protein' => 6.0, 'fat' => 4.0],
            ['name' => 'Susu Kedelai', 'calories' => 54, 'carbs' => 6.0, 'protein' => 3.3, 'fat' => 1.8],
            ['name' => 'Susu Sapi Segar', 'calories' => 61, 'carbs' => 4.8, 'protein' => 3.2, 'fat' => 3.3],
            ['name' => 'Tahu Bacem', 'calories' => 90, 'carbs' => 8.0, 'protein' => 8.0, 'fat' => 2.5],
            ['name' => 'Tahu Goreng', 'calories' => 115, 'carbs' => 2.2, 'protein' => 10.5, 'fat' => 7.8],
            ['name' => 'Tahu Telur', 'calories' => 180, 'carbs' => 10.0, 'protein' => 12.0, 'fat' => 10.0],
            ['name' => 'Talas Bogor, Kukus', 'calories' => 112, 'carbs' => 26.5, 'protein' => 1.0, 'fat' => 0.1],
            ['name' => 'Tekwan', 'calories' => 120, 'carbs' => 15.0, 'protein' => 8.0, 'fat' => 3.0],
            ['name' => 'Telur Ayam Dadar', 'calories' => 154, 'carbs' => 1.6, 'protein' => 12.0, 'fat' => 11.0],
            ['name' => 'Telur Balado', 'calories' => 160, 'carbs' => 4.0, 'protein' => 12.5, 'fat' => 10.5],
            ['name' => 'Telur Bebek Asin', 'calories' => 135, 'carbs' => 1.5, 'protein' => 12.0, 'fat' => 9.0],
            ['name' => 'Telur Dadar', 'calories' => 154, 'carbs' => 1.6, 'protein' => 12.0, 'fat' => 11.0],
            ['name' => 'Telur Dadar Padang', 'calories' => 200, 'carbs' => 5.0, 'protein' => 10.0, 'fat' => 15.0],
            ['name' => 'Tempe Geprek', 'calories' => 220, 'carbs' => 10.0, 'protein' => 15.0, 'fat' => 13.0],
            ['name' => 'Tempe Goreng', 'calories' => 150, 'carbs' => 9.1, 'protein' => 14.0, 'fat' => 7.5],
            ['name' => 'Teri Belado', 'calories' => 250, 'carbs' => 10.0, 'protein' => 20.0, 'fat' => 14.0],
            ['name' => 'Tongseng Sapi', 'calories' => 200, 'carbs' => 7.0, 'protein' => 18.0, 'fat' => 11.0],
            ['name' => 'Tumis Bandeng', 'calories' => 180, 'carbs' => 2.0, 'protein' => 20.0, 'fat' => 10.0],
            ['name' => 'Tumis Keumamah', 'calories' => 170, 'carbs' => 5.0, 'protein' => 22.0, 'fat' => 7.0],
            ['name' => 'Tumis Kangkung', 'calories' => 46, 'carbs' => 4.3, 'protein' => 3.0, 'fat' => 2.2],
            ['name' => 'Tumis Udang Buncis', 'calories' => 100, 'carbs' => 8.0, 'protein' => 12.0, 'fat' => 2.5],
            ['name' => 'Udang Balado', 'calories' => 140, 'carbs' => 6.0, 'protein' => 18.0, 'fat' => 5.0],
            ['name' => 'Udang Saus Padang', 'calories' => 120, 'carbs' => 8.0, 'protein' => 15.0, 'fat' => 3.5],
            ['name' => 'Udang Tepung Saus Lemon', 'calories' => 220, 'carbs' => 20.0, 'protein' => 15.0, 'fat' => 9.0],
            ['name' => 'Wajit Camilan', 'calories' => 250, 'carbs' => 55.0, 'protein' => 2.0, 'fat' => 3.0],
            ['name' => 'Widaran', 'calories' => 480, 'carbs' => 65.0, 'protein' => 6.0, 'fat' => 22.0],
            ['name' => 'Wingko Babat', 'calories' => 350, 'carbs' => 60.0, 'protein' => 5.0, 'fat' => 10.0],
            ['name' => 'Yangko', 'calories' => 200, 'carbs' => 45.0, 'protein' => 2.0, 'fat' => 1.0],
            ['name' => 'Zuppa Soup', 'calories' => 350, 'carbs' => 30.0, 'protein' => 10.0, 'fat' => 20.0],
        ];

        // Masukkan semua data ke dalam tabel 'foods'
        DB::table('foods')->insert($foods);
    }
}